#!/bin/bash

PKG=xdusage
mkdir -p tmp_rpm/$PKG_rpmtopdir
mkdir -p tmp_rpm/$PKG_rpmtopdir/BUILD
mkdir -p tmp_rpm/$PKG_rpmtopdir/SOURCES
mkdir -p tmp_rpm/$PKG_rpmtopdir/BUILDROOT
mkdir -p tmp_rpm/$PKG_rpmtopdir/RPMS
mkdir -p tmp_rpm/$PKG_rpmtopdir/SPECS
mkdir -p tmp_rpm/$PKG_rpmtopdir/SRPMS
cp $PKG-%VER%-%REL%.tgz tmp_rpm/$PKG_rpmtopdir/SOURCES
rpmbuild --quiet --define "_topdir ${PWD}/tmp_rpm/$PKG_rpmtopdir" -ba ./$PKG-%VER%/sbin/$PKG.spec
