#!/bin/sh

#echo "This script needs to be replaced with RPM generation and upload (JP 1/13/2014)"
#exit 1

if [ ! -e VERSION ]; then
  echo "You may be in the wrong directory."
  echo "Run tar from the package root."
  exit 1
fi

PKG=xdusage
VER=$(cat VERSION)
REL=$(cat RELEASE)

HERE=`pwd`
OUTDIR="tmp/xdusage-$VER-$REL/"

if [ -e $OUTDIR ]; then
  echo "Previous '$OUTDIR/' directory found, delete it first"
  exit 1
fi

mkdir -p $OUTDIR || exit 1

cp -p VERSION RELEASE $OUTDIR/

mkdir $OUTDIR/bin
mkdir $OUTDIR/docs

FILES=$(find bin docs -type f ! -path \*CVS\*)
for i in $FILES;do
  iout=$(echo $i | sed 's/\.in$//')
  sed -e "s,%VER%,$VER,g" \
      -e "s,%REL%,$REL,g" \
      $i \
      >$OUTDIR/$iout
done
mv $OUTDIR/docs/README $OUTDIR/INSTALL
 man $OUTDIR/docs/xdusage.1 >$OUTDIR/docs/xdusage.manpage
chmod +x $OUTDIR/bin/install.pl

#cd $OUTDIR
#tar -czf $PKG-$VER-$REL.tgz bin/* docs/* 
#cd $HERE
cd tmp
tar -czvf $PKG-$VER-$REL.tgz $PKG-$VER-$REL
cd $HERE
