#!/bin/sh -x

echo "This script needs to be replaced with RPM generation and upload (JP 1/13/2014)"
exit 1

if [ ! -e VERSION ]; then
  echo "You may not be in the right place to run upload"
  echo "Please run from the root of the package"
  exit 1
fi

PKG=xdusage
VER=$(cat VERSION)
REL=$(cat RELEASE)

REPO=software.teragrid.org
#REPO=localhost

REPO_SOFTWARE=/local/software.teragrid.org/software/$PKG
REPO_SUBDIR=$PKG-$VER-$REL

OUTDIR=tmp/$PKG-$VER-$REL/
if [ ! -d $OUTDIR ]; then
  echo "Package directory '$OUTDIR' missing"
  exit 1
fi

ssh $REPO mkdir $REPO_SOFTWARE/$REPO_SUBDIR

scp -p tmp/$PKG-$VER-$REL.tgz $REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p $OUTDIR/docs/* $REPO:$REPO_SOFTWARE/$REPO_SUBDIR/
scp -p $OUTDIR/INSTALL $REPO:$REPO_SOFTWARE/$REPO_SUBDIR/

ssh $REPO "cd $REPO_SOFTWARE; rm latest; ln -s $REPO_SUBDIR latest"
ssh $REPO "cd $REPO_SOFTWARE; ln -fs latest/INSTALL* ./"
